server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        -id: host_route
        uri: http://www.baidu.com
        predicates:
          -Method = GET
