server:
  port: 8081
eureka:
  client:
    service-url:
      # 配置eureka服务器地址
      defaultZone: http://127.0.0.1:8081/eureka
    # 是否将自己注册到注册中心
    register-with-eureka: false
    # 是否搜索服务信息
    fetch-registry: false